Class commande.msg.ajouterVoitureCatalogueDmde Extends Ens.Request
{

Property catalogue As commande.webObjet.wsCatalogue;

Storage Default
{
<Data name="ajouterVoitureCatalogueDmdeDefaultData">
<Subscript>"ajouterVoitureCatalogueDmde"</Subscript>
<Value name="1">
<Value>voiture</Value>
</Value>
<Value name="2">
<Value>catalogue</Value>
</Value>
</Data>
<DefaultData>ajouterVoitureCatalogueDmdeDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
