Class commande.msg.consulterVoitureCatalogueRpse Extends commande.msg.basic.reponse
{

Property catalogue As commande.webObjet.wsCatalogue;

Storage Default
{
<Data name="consulterVoitureCatalogueRpseDefaultData">
<Subscript>"consulterVoitureCatalogueRpse"</Subscript>
<Value name="1">
<Value>voiture</Value>
</Value>
<Value name="2">
<Value>catalogue</Value>
</Value>
</Data>
<DefaultData>consulterVoitureCatalogueRpseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
